dmioscope: propagate OSError from _get_cmd_output()
The _get_cmd_output() function transforms OSError into a
DmStatsException: instead, allow the OSError to propagate upward
since it indicates something more fundamentally wrong (inability
to fork or exec).